# Generated by Django 6.0.4 on 2026-04-24 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idade', models.IntegerField()),
                ('genero', models.CharField(max_length=100)),
                ('horas_estudadas', models.DecimalField(decimal_places=1, max_digits=5)),
                ('nivel_estresse', models.DecimalField(decimal_places=1, max_digits=5)),
                ('tempo_tela', models.DecimalField(decimal_places=1, max_digits=5)),
                ('ultimo_gpa', models.DecimalField(decimal_places=1, max_digits=5)),
                ('trabalho', models.BooleanField(default=False)),
            ],
        ),
    ]
