# Generated by Django 6.0.4 on 2026-04-24 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datamodels',
            name='ansiedade',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='datamodels',
            name='dieta',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='datamodels',
            name='internet',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='datamodels',
            name='metodo_estudo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='datamodels',
            name='pontos_final',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='datamodels',
            name='quant_aulas_paritic',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datamodels',
            name='renda_familiar',
            field=models.CharField(default='', max_length=15),
        ),
    ]
