# Generated by Django 6.0.4 on 2026-04-24 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_datamodels_ansiedade_datamodels_dieta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datamodels',
            name='extracurricular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datamodels',
            name='frequencia',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='datamodels',
            name='horas_sono',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
