# Generated by Django 6.0.4 on 2026-04-24 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_datamodels_extracurricular_datamodels_frequencia_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataModels',
        ),
    ]
