# Generated by Django 6.0.4 on 2026-04-24 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataModels',
        ),
    ]
