# Generated by Django 6.0.4 on 2026-04-24 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0006_delete_datamodels'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idade', models.IntegerField()),
                ('genero', models.CharField(max_length=100)),
                ('horas_estudadas', models.DecimalField(decimal_places=1, max_digits=5)),
                ('frequencia', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('horas_sono', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('nivel_estresse', models.DecimalField(decimal_places=1, max_digits=5)),
                ('tempo_tela', models.DecimalField(decimal_places=1, max_digits=5)),
                ('ultimo_gpa', models.DecimalField(decimal_places=1, max_digits=5)),
                ('trabalho', models.BooleanField(default=False)),
                ('metodo_estudo', models.CharField(default='', max_length=100)),
                ('dieta', models.CharField(default='', max_length=100)),
                ('internet', models.CharField(default='', max_length=100)),
                ('extracurricular', models.BooleanField(default=False)),
                ('quant_aulas_paritic', models.IntegerField(default=0)),
                ('renda_familiar', models.CharField(default='', max_length=15)),
                ('ansiedade', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('pontos_final', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
            ],
        ),
    ]
