# Generated by Django 6.0.4 on 2026-04-24 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datamodels',
            old_name='quant_aulas_paritic',
            new_name='quant_aulas_partic',
        ),
    ]
