# Generated by Django 6.0.4 on 2026-04-25 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_rename_quant_aulas_paritic_datamodels_quant_aulas_partic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamodels',
            name='genero',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='datamodels',
            name='horas_estudadas',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='datamodels',
            name='idade',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='datamodels',
            name='nivel_estresse',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='datamodels',
            name='tempo_tela',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='datamodels',
            name='ultimo_gpa',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
    ]
