# Generated by Django 6.0.4 on 2026-04-25 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_alter_datamodels_genero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamodels',
            name='ansiedade',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='datamodels',
            name='frequencia',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='datamodels',
            name='horas_estudadas',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='datamodels',
            name='horas_sono',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='datamodels',
            name='nivel_estresse',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='datamodels',
            name='pontos_final',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='datamodels',
            name='tempo_tela',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='datamodels',
            name='ultimo_gpa',
            field=models.FloatField(default=0.0),
        ),
    ]
